name: Whispr CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --omit=optional
          npm install --save-dev rollup@2.79.1
        env:
          ROLLUP_NO_NATIVE: 1

      - name: Build the app
        run: npm run build
        env:
          ROLLUP_NO_NATIVE: 1
