name: Whispr CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean node_modules and lockfiles
        run: rm -rf node_modules package-lock.json yarn.lock

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --ignore-optional

      - name: Print dependency tree (debug only)
        run: yarn list || true

      - name: Build
        run: yarn build
