name: Whispr CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install with Rollup workaround
        run: |
          rm -rf node_modules
          rm -f package-lock.json yarn.lock
          yarn cache clean
          yarn install --ignore-optional
        env:
          ROLLUP_NO_NATIVE: 1

      - name: Build the project
        run: yarn build
        env:
          ROLLUP_NO_NATIVE: 1
