name: Whispr CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean lockfiles and node_modules   # <--- ADD THIS HERE
        run: rm -rf node_modules package-lock.json yarn.lock

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --ignore-optional
        env:
          ROLLUP_NO_NATIVE: "1"

      - name: Build
        run: yarn build
        env:
          ROLLUP_NO_NATIVE: "1"
